import { food } from "./shared/model/food";
export const sample_foods:food[]=[
    {
        id:1,
        name: 'Pizza Pepperoni',
        cookTime: 10-20,
        price: 10,
        favorite: false,
        origins: 'italy',
        stars: 4.5,
        imageUrl: 'assets/images.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:2,
        name: 'Meatball',
        price: 20,
        cookTime: 20-30,
        favorite: true,
        origins: 'persia', 
        stars: 4.7,
        imageUrl: 'assets/download.jpg',
        tags: ['SlowFood', 'Lunch'],
      },
      {
        id:3,
        name: 'Hamburger',
        price: 5,
        cookTime: 10-15,
        favorite: false,
        origins: 'germany',
        stars: 3.5,
        imageUrl: 'assets/istockphoto-1192094401-612x612.jpg',
        tags: ['FastFood', 'Hamburger'],
      },
      {
        id:4,
        name: 'Fried Potatoes',
        price: 2,
        cookTime: 15-20,
        favorite: true,
        origins: 'belgium',
        stars: 3.3,
        imageUrl: 'assets/pizza-3007395_1280.jpg',
        tags: ['FastFood', 'Fry'],
      },
      {
        id:5,
        name: 'Chicken Soup',
        price: 11,
        cookTime: 40-50,
        favorite: false,
        origins: 'india',
        stars: 3.0,
        imageUrl: 'assets/pngtree-seafood-vegetable-pizza-gourmet-background-poster-image_214182.jpg',
        tags: ['SlowFood', 'Soup'],
      },
      {
        id:6,
        name: 'Vegetables Pizza',
        price: 9,
        cookTime: 40-50,
        favorite: false,
        origins: 'italy',
        stars: 4.0,
        imageUrl: 'assets/download.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },
      {
        id:7,
        name: 'Spicy Cheese Burger',
        price: 12,
        cookTime: 20-30,
        favorite: false,
        origins:'Indian',
        stars: 4.0,
        imageUrl: 'assets/istockphoto-1192094401-612x612.jpg',
        tags: ['FastFood', 'Burger', 'Lunch'],
      },
      {
        id:8,
        name: 'Vegetables Magento Pizza',
        price: 9,
        cookTime: 45-50,
        favorite: false,
        origins: 'indian',
        stars: 4.0,
        imageUrl: 'assets/images.jpg',
        tags: ['FastFood', 'Pizza', 'Lunch'],
      },

    

]